title : "Linq 사용법"
name  : "Sungchool Park"
lang: ko
description: "Linq 사용법 Using C#"

url     : "https://grimhang.github.io"
baseurl : "/LinqPractice"


#theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme
# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

#disqus_shortname: 'linq-sayongbeob'
---
layout: default
comments: true
# other options
---